# Generated by Django 5.1.3 on 2025-02-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('word_type', models.CharField(max_length=50)),
                ('meaning', models.TextField()),
                ('translates', models.CharField(max_length=100)),
            ],
        ),
    ]
