# Generated by Django 5.1.3 on 2025-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wordbank',
            constraint=models.UniqueConstraint(fields=('word', 'word_type'), name='unique_word'),
        ),
    ]
