# Generated by Django 5.1.3 on 2025-02-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbank', '0002_wordbank_unique_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbank',
            name='word_type',
            field=models.CharField(choices=[('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('determiner', 'Determiner'), ('phrase', 'Phrase'), ('modal verb', 'Modal Verb'), ('article', 'Article'), ('quantifier', 'Quantifier'), ('exclamatory word', 'Exclamatory Word'), ('gerund', 'Gerund'), ('infinitive', 'Infinitive'), ('relative pronoun', 'Relative Pronoun'), ('relative adverb', 'Relative Adverb'), ('prepositional phrase', 'Prepositional Phrase'), ('conjunction adverb', 'Conjunction Adverb'), ('correlative conjunction', 'Correlative Conjunction'), ('conditional', 'Conditional'), ('subjunctive mood', 'Subjunctive Mood'), ('indefinite pronoun', 'Indefinite Pronoun'), ('causative verb', 'Causative Verb'), ('intensifier', 'Intensifier')], max_length=50),
        ),
    ]
