# Generated by Django 5.1.4 on 2025-02-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergame', '0001_userscore'),
        ('user', '0003_flashcarduserscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='sentence',
            field=models.ManyToManyField(to='ordergame.sentences'),
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='user',
        ),
        migrations.AddField(
            model_name='userscore',
            name='user',
            field=models.ManyToManyField(to='user.account'),
        ),
    ]
