# Generated by Django 5.1.4 on 2025-02-17 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergame', '0002_userscore_sentence_remove_userscore_user_and_more'),
        ('user', '0003_flashcarduserscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderUserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('times', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordergame.sentences')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
            ],
            options={
                'unique_together': {('user', 'sentence')},
            },
        ),
        migrations.DeleteModel(
            name='userScore',
        ),
    ]
