# Generated by Django 5.1.4 on 2025-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='flashcard',
        ),
        migrations.AddField(
            model_name='account',
            name='flashcard',
            field=models.ManyToManyField(to='flashcard.flashcarddeck'),
        ),
    ]
