# Generated by Django 5.1.4 on 2025-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_account_flashcard_account_flashcard'),
        ('wordbank', '0003_alter_wordbank_word_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='flashcardUserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('answerCount', models.IntegerField()),
                ('account', models.ManyToManyField(to='user.account')),
                ('words', models.ManyToManyField(to='wordbank.wordbank')),
            ],
        ),
    ]
