# Generated by Django 5.1.3 on 2025-02-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_flashcarduserscore'),
        ('wordbank', '0003_alter_wordbank_word_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='fail_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fails', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.account')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbank.wordbank')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'word'), name='unique_nw')],
            },
        ),
    ]
